//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEDSVoucherSalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FEDSVoucherSalesOrder()
        {
            this.MemberFEDSVoucher = new HashSet<MemberFEDSVoucher>();
        }
    
        public string SalesOrderNo { get; set; }
        public int OrderStatus { get; set; }
        public int PaymentType { get; set; }
        public int MemberId { get; set; }
        public int MallId { get; set; }
        public int FEDSVoucherId { get; set; }
        public int TotalQty { get; set; }
        public System.DateTime SalesDate { get; set; }
        public int CarrierType { get; set; }
        public string CarrierId { get; set; }
        public int TotalPrice { get; set; }
        public int TotalHGPoint { get; set; }
        public string ECPayTradeNo { get; set; }
        public Nullable<System.DateTime> ECPayPaymentDate { get; set; }
        public string ECPayPaymentType { get; set; }
        public Nullable<System.DateTime> ECPayTradeDate { get; set; }
        public string ECPayTradeStatus { get; set; }
        public Nullable<int> ECPayCreditRefundId { get; set; }
        public Nullable<int> ECPayRtnCode { get; set; }
        public string ECPayRtnMsg { get; set; }
        public string ECPayCard4no { get; set; }
        public Nullable<bool> CheckECPay { get; set; }
        public Nullable<bool> IsECPaySuccess { get; set; }
        public Nullable<bool> IsHGRedeemSuccess { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberFEDSVoucher> MemberFEDSVoucher { get; set; }
    }
}
