//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGame.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftsEntities : DbContext
    {
        public GiftsEntities()
            : base("name=GiftsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coupon> Coupon { get; set; }
        public virtual DbSet<Coupon_Log> Coupon_Log { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<EntityPresent> EntityPresent { get; set; }
        public virtual DbSet<Gifts> Gifts { get; set; }
        public virtual DbSet<HGRecord> HGRecord { get; set; }
        public virtual DbSet<HGRecord_Log> HGRecord_Log { get; set; }
        public virtual DbSet<MainCategory> MainCategory { get; set; }
        public virtual DbSet<Mall> Mall { get; set; }
        public virtual DbSet<MiddleCategory> MiddleCategory { get; set; }
        public virtual DbSet<SystemExchangeLog> SystemExchangeLog { get; set; }
        public virtual DbSet<PosToken> PosToken { get; set; }
        public virtual DbSet<SystemErrorLog> SystemErrorLog { get; set; }
        public virtual DbSet<UsedRule> UsedRule { get; set; }
    }
}
