//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFEDSVoucherHistory
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int MemberFEDSVoucherId { get; set; }
        public string SalesOrderNo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
        public bool IsGenerateInvoice { get; set; }
        public string Creator { get; set; }
        public string Remark { get; set; }
    
        public virtual MemberFEDSVoucher MemberFEDSVoucher { get; set; }
    }
}
