//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFEDSVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberFEDSVoucher()
        {
            this.MemberFEDSVoucherHistory = new HashSet<MemberFEDSVoucherHistory>();
        }
    
        public int Id { get; set; }
        public int MemberId { get; set; }
        public string FEDSVoucherSalesOrderNo { get; set; }
        public int FEDSVoucherId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string VoucherNo { get; set; }
        public int Status { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int UnitPrice { get; set; }
        public int HGPoint { get; set; }
        public int VoucherModifyType { get; set; }
    
        public virtual FEDSVoucherSalesOrder FEDSVoucherSalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberFEDSVoucherHistory> MemberFEDSVoucherHistory { get; set; }
    }
}
